### ISSUE TITLE
Unable to build vlingo-e2e-sys-airline-ops

### ISSUE THREAD

**Issue by cranberrysoft** [vlingo/vlingo-examples#96] opened 2021-02-18 10:52 UTC
Hi,
I tried to build the _vlingo-e2e-sys-airline-ops_ project from the master branch, but it constantly fails with the following error.

```
[INFO] Reactor Summary for vlingo-e2e-sys-airline-ops 1.5.1-SNAPSHOT:
[INFO] 
[INFO] vlingo-e2e-sys-airline-ops ......................... SUCCESS [  0.295 s]
[INFO] inventory .......................................... SUCCESS [ 10.751 s]
[INFO] airport-terminal ................................... SUCCESS [  7.331 s]
[INFO] air-traffic-control ................................ FAILURE [  8.895 s]
[INFO] fleetcrew .......................................... SKIPPED
[INFO] flight-planning .................................... SKIPPED
[INFO] aircraft-monitoring ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  27.396 s
[INFO] Finished at: 2021-02-18T21:44:07+11:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.vlingo:vlingo-build-plugins:1.5.1-SNAPSHOT:push-schemata (default) on project air-traffic-control: Could not push SchemaVersion to http://localhost:9019/api/versions/SkyHarborPHX:groundops:com.skyharbor.airtrafficcontrol:OutboundTaxingInitiated:1.0.0: Internal Server Error - 500 -> [Help 1]
```

I run db,rabitmq and schemata using the docker-compose from the project. In the schemata logs the last log I is
`Publication date: 2021-02-18T21:43:51.377424, specification=event AircraftConsigned {
  version semanticVersion
  string aircraftId
  string model
  string serialNumber
  string tailNumber
}, status=Draft, previousVersion=0.0.0, currentVersion=1.0.0]]]`

besides this, a bunch of errors like
`io.vlingo.symbio.store.StorageException: ERROR: duplicate key value violates unique constraint `

the same for the db logs
`2021-02-18 10:44:11.679 UTC [33] ERROR:  duplicate key value violates unique constraint "tbl_vlingo_symbio_dispatchables_pkey"`

I would appreciate any help.

**Comment by jakzal** [comment] 2021-02-18 11:51
I couldn't reproduce it. Can you try removing docker containers with volumes and starting it again?

```
docker-compose stop
docker-compose rm -v
docker-compose up -d
```

**Comment by danilo-ambrosio** [comment] 2021-02-18 15:00
@jakzal Thanks for your guidance. 

I think what's happening. The README was a bit outdated.

@cranberrysoft Besides the @jakzal approach, please consider the updated instructions to run the "aircraft-airport-ops" services:

_In the root folder, execute `docker-compose up -d` so that all infrastructure resources (Postgres DB, Schemata and RabbitMQ) will be installed and initialized. Then, run the following maven build goal:_

```
$ mvn clean package
```

_Finally, run each service through the executable `jar` passing a port number:_

```
$ java -jar [service-folder-name]/target/[jar-name].jar [port-number]
```

**Note that you should use the `package` goal instead of `install`**.


Please let me know if it's working fine now.

**Comment by cranberrysoft** [comment] 2021-02-18 18:00
Thanks, it has solved the issue! I think somehow the containers were stale and the docker-compose commands helped.

**Closed** 2021-02-18 18:01 UTC
